# Site settings
title: Optimistic Nihilist
email: vcavallo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This block of text is for testing deploy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://optimisticnihilist.com" # the base hostname & protocol for your site
twitter_username: vcavallo

# Build settings
markdown: kramdown
